"use client";

import { FormEvent, useState } from "react";

type Form = {
  name: string; dob: string; time: string; place: string; gender: string;
  father: string; mother: string; headline: string; sentence: string;
  shopName: string; shopPlace: string; shopContact: string;
};

const initial: Form = {
  name:"", dob:"", time:"", place:"", gender:"ஆண்", father:"", mother:"",
  headline:"", sentence:"", shopName:"", shopPlace:"", shopContact:""
};

/*
  Real image assets are NOT generated by this program.
  These are existing Wikimedia Commons images:
  Murugan: public domain
  Ganesha: CC0
  The URLs can later be replaced with /murugan.jpg and /vinayagar.jpg
  if you want to keep the images locally inside your own project.
*/
const MURUGAN_IMAGE =
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Lord_Muruga.jpg";
const VINAYAGAR_IMAGE =
  "https://commons.wikimedia.org/wiki/Special:Redirect/file/Ganesha_picture.jpg";

function Field({label,value,onChange,placeholder,type="text",optional=false}:{
  label:string; value:string; onChange:(v:string)=>void; placeholder?:string;
  type?:string; optional?:boolean;
}) {
  return <label className="field">
    <span>{label}{optional && <em> (விருப்பம்)</em>}</span>
    <input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} />
  </label>;
}

function Deity({src,label}:{src:string;label:string}) {
  return <div className="deity">
    <div className="deity-ring">
      <img src={src} alt={label} />
    </div>
    <small>{label}</small>
  </div>;
}

export default function Home() {
  const [f,setF] = useState<Form>(initial);
  const [report,setReport] = useState(false);
  const set = (k:keyof Form)=>(v:string)=>setF(x=>({...x,[k]:v}));

  function submit(e:FormEvent) {
    e.preventDefault();
    if (!f.name || !f.dob || !f.time || !f.place) {
      alert("பெயர், பிறந்த தேதி, பிறந்த நேரம், பிறந்த இடம் ஆகியவை கட்டாயம்.");
      return;
    }
    setReport(true);
    setTimeout(()=>document.getElementById("report")?.scrollIntoView({behavior:"smooth"}),50);
  }

  return <main>
    <section className="editor no-print">
      <div className="brand">
        <b>KINGS TECHNOLOGY</b>
        <h1>ஒரு பக்க ஜாதகம்</h1>
        <p>Professional Tamil Astrology Report</p>
      </div>

      <form onSubmit={submit}>
        <h2>பிறப்பு விவரங்கள்</h2>
        <div className="form-grid">
          <Field label="பெயர்" value={f.name} onChange={set("name")} placeholder="உதா: KESAVAN" />
          <Field label="பிறந்த தேதி" value={f.dob} onChange={set("dob")} type="date" />
          <Field label="பிறந்த நேரம்" value={f.time} onChange={set("time")} type="time" />
          <Field label="பிறந்த இடம்" value={f.place} onChange={set("place")} placeholder="உதா: SALEM" />
          <label className="field"><span>பாலினம்</span>
            <select value={f.gender} onChange={e=>set("gender")(e.target.value)}>
              <option>ஆண்</option><option>பெண்</option>
            </select>
          </label>
          <Field label="தந்தை பெயர்" value={f.father} onChange={set("father")} optional />
          <Field label="தாய் பெயர்" value={f.mother} onChange={set("mother")} optional />
        </div>

        <h2>கூடுதல் விவரங்கள்</h2>
        <div className="form-grid">
          <Field label="Bold Headline" value={f.headline} onChange={set("headline")} placeholder="உதா: சிறப்பான எதிர்காலம்" optional />
          <Field label="ஒரு வரி வாசகம்" value={f.sentence} onChange={set("sentence")} placeholder="உங்கள் விருப்ப வாசகம்..." optional />
        </div>

        <h2>Shop / ஜோதிடர் விவரங்கள்</h2>
        <div className="form-grid">
          <Field label="Shop Name" value={f.shopName} onChange={set("shopName")} optional />
          <Field label="Shop Place" value={f.shopPlace} onChange={set("shopPlace")} optional />
          <Field label="Shop Contact" value={f.shopContact} onChange={set("shopContact")} optional />
        </div>

        <button className="generate" type="submit">ஜாதகத்தை உருவாக்கு</button>
      </form>
    </section>

    {report && <section id="report" className="a4">
      <header className="report-head">
        <Deity src={MURUGAN_IMAGE} label="ஸ்ரீ முருகன்" />
        <div className="head-center">
          <div className="tiny">ஜென்ம ஜாதகம் • KINGS TECHNOLOGY</div>
          <h1>ஒரு பக்க ஜாதகம்</h1>
          <div className="sub">பிறப்பு விவரங்களின் அடிப்படையில் உருவாக்கப்பட்ட ஜாதக அறிக்கை</div>
          {f.headline && <strong className="headline">{f.headline}</strong>}
          {f.sentence && <p className="sentence">{f.sentence}</p>}
        </div>
        <Deity src={VINAYAGAR_IMAGE} label="ஸ்ரீ விநாயகர்" />
      </header>

      <div className="rule" />

      <div className="info-grid">
        <Info label="பெயர்" value={f.name}/><Info label="பிறந்த தேதி" value={f.dob}/>
        <Info label="பிறந்த நேரம்" value={f.time}/><Info label="பிறந்த இடம்" value={f.place}/>
        <Info label="பாலினம்" value={f.gender}/>
        {f.father && <Info label="தந்தை" value={f.father}/>}
        {f.mother && <Info label="தாய்" value={f.mother}/>}
      </div>

      <div className="content-grid">
        <Panel title="கிரக நிலைகள்">
          <table><thead><tr><th>கிரகம்</th><th>ராசி</th><th>நட்சத்திரம்</th><th>பாதம்</th></tr></thead>
          <tbody>{["சூரியன்","சந்திரன்","செவ்வாய்","புதன்","குரு","சுக்கிரன்","சனி","ராகு","கேது"].map(p=>
            <tr key={p}><td>{p}</td><td>—</td><td>—</td><td>—</td></tr>
          )}</tbody></table>
        </Panel>

        <Panel title="ராசி கட்டம்"><SouthChart title="ராசி"/></Panel>
        <Panel title="நவாம்ச கட்டம்"><SouthChart title="நவாம்சம்"/></Panel>

        <Panel title="தசா இருப்பு">
          <div className="dash">
            <p><b>தற்போதைய தசா</b><span>—</span></p>
            <p><b>மீதம்</b><span>—</span></p>
            <p><b>அடுத்த தசா</b><span>—</span></p>
          </div>
        </Panel>
      </div>

      {(f.shopName || f.shopPlace || f.shopContact) && <footer className="shop-footer">
        {f.shopName && <b>{f.shopName}</b>}
        {f.shopPlace && <span>{f.shopPlace}</span>}
        {f.shopContact && <span>{f.shopContact}</span>}
      </footer>}

      <footer className="print-footer">
        <span>Generated: {new Date().toLocaleDateString("en-GB")}</span>
        <span>KINGS TECHNOLOGY</span>
        <span>ஒரு பக்க ஜாதகம்</span>
      </footer>
    </section>}

    {report && <div className="actions no-print">
      <button onClick={()=>window.print()}>Print / Save as PDF</button>
    </div>}
  </main>;
}

function Info({label,value}:{label:string;value:string}) {
  return <div className="info"><small>{label}</small><b>{value}</b></div>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}) {
  return <section className="panel"><h2>{title}</h2>{children}</section>;
}
function SouthChart({title}:{title:string}) {
  const cells=["மீனம்","மேஷம்","ரிஷபம்","மிதுனம்","கும்பம்","","","கடகம்","மகரம்","","","சிம்மம்","தனுசு","விருச்சிகம்","துலாம்","கன்னி"];
  return <div className="chart">{cells.map((x,i)=><div key={i} className={(i===5||i===6||i===9||i===10)?"empty":""}>{x}</div>)}<div className="chart-center">{title}</div></div>;
}
